version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/E-Commune
      # The backend application code (backend/models/dbConnection.js)
      # needs to be updated to use this MONGO_URI environment variable.
      # Example: const dbURI = process.env.MONGO_URI || 'mongodb://localhost:27017/E-Commune';
      # mongoose.connect(dbURI) ...
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # Optional: for connecting directly from the host
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
